# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tourpoints',
            new_name='Tourpoint',
        ),
    ]
